//export PATH="$PATH:$(go env GOPATH)/bin"
//sudo protoc --go_out=. --go_opt=paths=source_relative     --go-grpc_out=. --go-grpc_opt=paths=source_relative  neuroservice.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: neuroservice.proto

package neuro_pic_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalImage []byte `protobuf:"bytes,1,opt,name=OriginalImage,proto3" json:"OriginalImage,omitempty"`
	StyleImage    []byte `protobuf:"bytes,2,opt,name=StyleImage,proto3" json:"StyleImage,omitempty"`
}

func (x *GeneratePictureRequest) Reset() {
	*x = GeneratePictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neuroservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePictureRequest) ProtoMessage() {}

func (x *GeneratePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neuroservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePictureRequest.ProtoReflect.Descriptor instead.
func (*GeneratePictureRequest) Descriptor() ([]byte, []int) {
	return file_neuroservice_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePictureRequest) GetOriginalImage() []byte {
	if x != nil {
		return x.OriginalImage
	}
	return nil
}

func (x *GeneratePictureRequest) GetStyleImage() []byte {
	if x != nil {
		return x.StyleImage
	}
	return nil
}

type GeneratePictureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultImage []byte `protobuf:"bytes,1,opt,name=ResultImage,proto3" json:"ResultImage,omitempty"`
}

func (x *GeneratePictureResponse) Reset() {
	*x = GeneratePictureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neuroservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePictureResponse) ProtoMessage() {}

func (x *GeneratePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neuroservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePictureResponse.ProtoReflect.Descriptor instead.
func (*GeneratePictureResponse) Descriptor() ([]byte, []int) {
	return file_neuroservice_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePictureResponse) GetResultImage() []byte {
	if x != nil {
		return x.ResultImage
	}
	return nil
}

var File_neuroservice_proto protoreflect.FileDescriptor

var file_neuroservice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5e, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x3b, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x6c, 0x0a,
	0x0c, 0x4e, 0x65, 0x75, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x22, 0x2e, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x74, 0x6c, 0x2d, 0x79, 0x2f,
	0x6e, 0x65, 0x75, 0x72, 0x6f, 0x2d, 0x70, 0x69, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neuroservice_proto_rawDescOnce sync.Once
	file_neuroservice_proto_rawDescData = file_neuroservice_proto_rawDesc
)

func file_neuroservice_proto_rawDescGZIP() []byte {
	file_neuroservice_proto_rawDescOnce.Do(func() {
		file_neuroservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_neuroservice_proto_rawDescData)
	})
	return file_neuroservice_proto_rawDescData
}

var file_neuroservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_neuroservice_proto_goTypes = []interface{}{
	(*GeneratePictureRequest)(nil),  // 0: neuroproto.GeneratePictureRequest
	(*GeneratePictureResponse)(nil), // 1: neuroproto.GeneratePictureResponse
}
var file_neuroservice_proto_depIdxs = []int32{
	0, // 0: neuroproto.NeuroService.GeneratePicture:input_type -> neuroproto.GeneratePictureRequest
	1, // 1: neuroproto.NeuroService.GeneratePicture:output_type -> neuroproto.GeneratePictureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_neuroservice_proto_init() }
func file_neuroservice_proto_init() {
	if File_neuroservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neuroservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neuroservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePictureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neuroservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neuroservice_proto_goTypes,
		DependencyIndexes: file_neuroservice_proto_depIdxs,
		MessageInfos:      file_neuroservice_proto_msgTypes,
	}.Build()
	File_neuroservice_proto = out.File
	file_neuroservice_proto_rawDesc = nil
	file_neuroservice_proto_goTypes = nil
	file_neuroservice_proto_depIdxs = nil
}
